import dellLaptopImg from "@/assets/dell-laptop.png";
import hpLaptopImg from "@/assets/hp-laptop.png";
import lenovoLaptopImg from "@/assets/lenovo-laptop.png";
import macbookImg from "@/assets/macbook.png";
import cpuDesktopImg from "@/assets/cpu-desktop.png";
import printerImg from "@/assets/printer.png";
import accessoriesImg from "@/assets/accessories.png";
import servicePrinterImg from "@/assets/service-printer-repair.png";
import serviceCpuImg from "@/assets/service-cpu-repair.png";
import serviceLaptopImg from "@/assets/service-laptop-repair.png";

export interface Product {
  id: string;
  name: string;
  category: string;
  price: number;
  originalPrice?: number;
  image: string;
  images?: string[]; // Multiple images for gallery
  brand: string;
  ram?: string;
  storage?: string;
  specs: string[];
  description: string;
  rating: number;
  reviews: number;
  badge?: string;
}

export const categories = [
  { name: "CPU | Desktop Setup", slug: "cpu-desktop", image: cpuDesktopImg, subtitle: "High Performance Builds" },
  { name: "Dell Laptop", slug: "dell-laptop", image: dellLaptopImg, subtitle: "Official Partner & Sales" },
  { name: "HP Laptop", slug: "hp-laptop", image: hpLaptopImg, subtitle: "Latest Models & Repair" },
  { name: "Lenovo Laptop", slug: "lenovo-laptop", image: lenovoLaptopImg, subtitle: "Business & Gaming Series" },
  { name: "MacBook", slug: "macbook", image: macbookImg, subtitle: "Apple Certified Support" },
  { name: "Printers", slug: "printers", image: printerImg, subtitle: "Service & Troubleshooting" },
  { name: "Accessories", slug: "accessories", image: accessoriesImg, subtitle: "Keyboards, Mice & More" },
];

export const accessorySubtypes = [
  { label: "Keyboards", value: "keyboards" },
  { label: "Mouse", value: "mouse" },
  { label: "Headphones & Headsets", value: "headphones" },
  { label: "Webcams", value: "webcams" },
  { label: "Monitors", value: "monitors" },
  { label: "Speakers", value: "speakers" },
  { label: "USB Hubs & Adapters", value: "usb-hubs" },
  { label: "Bags & Sleeves", value: "bags" },
  { label: "Cables & Chargers", value: "cables" },
  { label: "Other Accessories", value: "accessories-other" },
];

export interface Service {
  id: string;
  name: string;
  description: string;
  image: string;
  icon: string;
}

export const services: Service[] = [
  {
    id: "laptop-repair",
    name: "Laptop Repair",
    description: "Expert diagnosis and repair for all laptop brands. Screen replacement, keyboard repair, motherboard fixing, and more.",
    image: serviceLaptopImg,
    icon: "laptop",
  },
  {
    id: "printer-repair",
    name: "Printer Repair",
    description: "Professional printer servicing and repair. Ink system fixes, paper jam solutions, and regular maintenance.",
    image: servicePrinterImg,
    icon: "printer",
  },
  {
    id: "cpu-repair",
    name: "CPU Repair",
    description: "Desktop and CPU troubleshooting, hardware upgrades, OS installation, and performance optimization.",
    image: serviceCpuImg,
    icon: "cpu",
  },
];

export const products: Product[] = [
  // CPU | Desktop Setup (5)
  {
    id: "1",
    name: "ProDesk Elite i9",
    category: "cpu-desktop",
    price: 89999,
    originalPrice: 99999,
    image: cpuDesktopImg,
    brand: "Chauhan",
    ram: "32GB",
    storage: "1TB SSD",
    specs: ["Intel Core i9-14900K", "32GB DDR5", "1TB NVMe SSD", "NVIDIA RTX 4070"],
    description: "High-performance desktop workstation built for professionals who demand uncompromising power.",
    rating: 4.9,
    reviews: 124,
    badge: "Best Seller",
  },
  {
    id: "2",
    name: "Studio Tower Pro",
    category: "cpu-desktop",
    price: 74999,
    image: cpuDesktopImg,
    brand: "Chauhan",
    ram: "64GB",
    storage: "2TB SSD",
    specs: ["AMD Ryzen 9 7950X", "64GB DDR5", "2TB NVMe SSD", "NVIDIA RTX 4080"],
    description: "Built for creative professionals. Handles 8K editing, 3D rendering, and complex simulations with ease.",
    rating: 4.8,
    reviews: 87,
    badge: "New",
  },
  {
    id: "3",
    name: "Compact Workstation",
    category: "cpu-desktop",
    price: 54999,
    image: cpuDesktopImg,
    brand: "Chauhan",
    ram: "32GB",
    storage: "1TB SSD",
    specs: ["Intel Core i7-14700", "32GB DDR5", "1TB NVMe SSD", "Intel Arc A770"],
    description: "Big performance in a small form factor. Fits anywhere without compromise.",
    rating: 4.5,
    reviews: 67,
  },
  {
    id: "4",
    name: "Gaming Beast X",
    category: "cpu-desktop",
    price: 129999,
    image: cpuDesktopImg,
    brand: "Chauhan",
    ram: "32GB",
    storage: "2TB SSD",
    specs: ["Intel Core i9-14900K", "32GB DDR5", "2TB NVMe SSD", "NVIDIA RTX 4090"],
    description: "Dominate every game with desktop-class performance and custom liquid cooling.",
    rating: 4.9,
    reviews: 203,
  },
  {
    id: "5",
    name: "Office Desktop Basic",
    category: "cpu-desktop",
    price: 32999,
    image: cpuDesktopImg,
    brand: "Chauhan",
    ram: "16GB",
    storage: "512GB SSD",
    specs: ["Intel Core i5-14400", "16GB DDR5", "512GB NVMe SSD", "Intel UHD 730"],
    description: "Reliable everyday computing for office and home use. Quiet and efficient.",
    rating: 4.3,
    reviews: 312,
  },

  // Dell Laptop (5)
  {
    id: "6",
    name: "Dell Inspiron 15",
    category: "dell-laptop",
    price: 49999,
    originalPrice: 55999,
    image: dellLaptopImg,
    brand: "Dell",
    ram: "16GB",
    storage: "512GB SSD",
    specs: ["Intel Core i5-1335U", "16GB DDR5", "512GB NVMe SSD", "15.6\" FHD IPS"],
    description: "Versatile everyday laptop with solid performance and vibrant display for work and entertainment.",
    rating: 4.4,
    reviews: 456,
    badge: "Popular",
  },
  {
    id: "7",
    name: "Dell Latitude 14",
    category: "dell-laptop",
    price: 72999,
    image: dellLaptopImg,
    brand: "Dell",
    ram: "16GB",
    storage: "512GB SSD",
    specs: ["Intel Core i7-1365U", "16GB DDR5", "512GB NVMe SSD", "14\" FHD+"],
    description: "Business-grade laptop built for security, manageability, and all-day battery life.",
    rating: 4.6,
    reviews: 189,
  },
  {
    id: "8",
    name: "Dell XPS 15",
    category: "dell-laptop",
    price: 134999,
    originalPrice: 149999,
    image: dellLaptopImg,
    brand: "Dell",
    ram: "32GB",
    storage: "1TB SSD",
    specs: ["Intel Core i7-13700H", "32GB DDR5", "1TB NVMe SSD", "15.6\" 3.5K OLED"],
    description: "Premium ultrabook with stunning OLED display and powerhouse performance in a thin design.",
    rating: 4.8,
    reviews: 298,
    badge: "Premium",
  },
  {
    id: "9",
    name: "Dell Vostro 14",
    category: "dell-laptop",
    price: 44999,
    image: dellLaptopImg,
    brand: "Dell",
    ram: "8GB",
    storage: "512GB SSD",
    specs: ["Intel Core i5-1335U", "8GB DDR4", "512GB NVMe SSD", "14\" FHD"],
    description: "Small business laptop with essential features and reliable performance at a great value.",
    rating: 4.2,
    reviews: 134,
  },
  {
    id: "10",
    name: "Dell G15 Gaming",
    category: "dell-laptop",
    price: 89999,
    image: dellLaptopImg,
    brand: "Dell",
    ram: "16GB",
    storage: "1TB SSD",
    specs: ["Intel Core i7-13650HX", "16GB DDR5", "1TB NVMe SSD", "NVIDIA RTX 4060"],
    description: "Gaming laptop with high-refresh display and powerful graphics for immersive gameplay.",
    rating: 4.5,
    reviews: 267,
    badge: "Gaming",
  },

  // HP Laptop (4)
  {
    id: "11",
    name: "HP Pavilion 15",
    category: "hp-laptop",
    price: 47999,
    originalPrice: 52999,
    image: hpLaptopImg,
    brand: "HP",
    ram: "16GB",
    storage: "512GB SSD",
    specs: ["AMD Ryzen 5 7530U", "16GB DDR4", "512GB NVMe SSD", "15.6\" FHD IPS"],
    description: "Everyday laptop with AMD power, vibrant display, and sleek design for work and play.",
    rating: 4.3,
    reviews: 389,
  },
  {
    id: "12",
    name: "HP EliteBook 840",
    category: "hp-laptop",
    price: 94999,
    image: hpLaptopImg,
    brand: "HP",
    ram: "16GB",
    storage: "512GB SSD",
    specs: ["Intel Core i7-1365U", "16GB DDR5", "512GB NVMe SSD", "14\" WUXGA"],
    description: "Enterprise-grade ultrabook with advanced security features and premium build quality.",
    rating: 4.7,
    reviews: 156,
    badge: "Business",
  },
  {
    id: "13",
    name: "HP Spectre x360",
    category: "hp-laptop",
    price: 119999,
    image: hpLaptopImg,
    brand: "HP",
    ram: "16GB",
    storage: "1TB SSD",
    specs: ["Intel Core i7-1355U", "16GB LPDDR5", "1TB NVMe SSD", "13.5\" 3K2K OLED"],
    description: "Stunning convertible laptop with gem-cut design and brilliant OLED touchscreen.",
    rating: 4.8,
    reviews: 201,
    badge: "Premium",
  },
  {
    id: "14",
    name: "HP Victus 16 Gaming",
    category: "hp-laptop",
    price: 79999,
    originalPrice: 89999,
    image: hpLaptopImg,
    brand: "HP",
    ram: "16GB",
    storage: "512GB SSD",
    specs: ["AMD Ryzen 7 7840HS", "16GB DDR5", "512GB NVMe SSD", "NVIDIA RTX 4050"],
    description: "Affordable gaming laptop with solid performance and 144Hz display for smooth gameplay.",
    rating: 4.4,
    reviews: 312,
    badge: "Value",
  },

  // Lenovo Laptop (2)
  {
    id: "15",
    name: "Lenovo ThinkPad X1 Carbon",
    category: "lenovo-laptop",
    price: 139999,
    image: lenovoLaptopImg,
    brand: "Lenovo",
    ram: "16GB",
    storage: "512GB SSD",
    specs: ["Intel Core i7-1365U", "16GB LPDDR5", "512GB NVMe SSD", "14\" 2.8K OLED"],
    description: "The gold standard in business ultrabooks. Ultra-light, ultra-durable, ultra-premium.",
    rating: 4.9,
    reviews: 445,
    badge: "Editor's Choice",
  },
  {
    id: "16",
    name: "Lenovo IdeaPad Slim 5",
    category: "lenovo-laptop",
    price: 54999,
    originalPrice: 59999,
    image: lenovoLaptopImg,
    brand: "Lenovo",
    ram: "16GB",
    storage: "512GB SSD",
    specs: ["AMD Ryzen 5 7530U", "16GB DDR4", "512GB NVMe SSD", "15.6\" FHD IPS"],
    description: "Slim and stylish everyday laptop with great battery life and performance for students and professionals.",
    rating: 4.4,
    reviews: 278,
  },

  // MacBook (6)
  {
    id: "17",
    name: "MacBook Air M2",
    category: "macbook",
    price: 99999,
    originalPrice: 114999,
    image: macbookImg,
    brand: "Apple",
    ram: "8GB",
    storage: "256GB SSD",
    specs: ["Apple M2 Chip", "8GB Unified Memory", "256GB SSD", "13.6\" Liquid Retina"],
    description: "Supercharged by M2 chip. Strikingly thin design with incredible performance and all-day battery life.",
    rating: 4.8,
    reviews: 892,
    badge: "Popular",
  },
  {
    id: "18",
    name: "MacBook Air M3",
    category: "macbook",
    price: 114999,
    image: macbookImg,
    brand: "Apple",
    ram: "8GB",
    storage: "256GB SSD",
    specs: ["Apple M3 Chip", "8GB Unified Memory", "256GB SSD", "13.6\" Liquid Retina"],
    description: "The most popular Mac, now with the M3 chip. Impossibly thin with stunning performance.",
    rating: 4.9,
    reviews: 567,
    badge: "New",
  },
  {
    id: "19",
    name: "MacBook Pro 14\" M3",
    category: "macbook",
    price: 169999,
    image: macbookImg,
    brand: "Apple",
    ram: "18GB",
    storage: "512GB SSD",
    specs: ["Apple M3 Pro Chip", "18GB Unified Memory", "512GB SSD", "14.2\" Liquid Retina XDR"],
    description: "Pro-level performance for demanding workflows. XDR display with ProMotion for the ultimate experience.",
    rating: 4.9,
    reviews: 723,
    badge: "Pro",
  },
  {
    id: "20",
    name: "MacBook Pro 16\" M3 Max",
    category: "macbook",
    price: 299999,
    image: macbookImg,
    brand: "Apple",
    ram: "36GB",
    storage: "1TB SSD",
    specs: ["Apple M3 Max Chip", "36GB Unified Memory", "1TB SSD", "16.2\" Liquid Retina XDR"],
    description: "The most powerful MacBook ever. Built for professionals who push the boundaries of what's possible.",
    rating: 5.0,
    reviews: 334,
    badge: "Ultimate",
  },
  {
    id: "21",
    name: "MacBook Air 15\" M3",
    category: "macbook",
    price: 134999,
    image: macbookImg,
    brand: "Apple",
    ram: "8GB",
    storage: "256GB SSD",
    specs: ["Apple M3 Chip", "8GB Unified Memory", "256GB SSD", "15.3\" Liquid Retina"],
    description: "Big, beautiful 15-inch display in an impossibly thin design. Perfect for multitasking.",
    rating: 4.7,
    reviews: 445,
  },
  {
    id: "22",
    name: "MacBook Pro 14\" M3 Pro",
    category: "macbook",
    price: 199999,
    originalPrice: 219999,
    image: macbookImg,
    brand: "Apple",
    ram: "18GB",
    storage: "1TB SSD",
    specs: ["Apple M3 Pro Chip", "18GB Unified Memory", "1TB SSD", "14.2\" Liquid Retina XDR"],
    description: "Enhanced M3 Pro with more storage. The professional's choice for creative work.",
    rating: 4.9,
    reviews: 198,
    badge: "Best Value",
  },

  // Printers (2)
  {
    id: "23",
    name: "HP LaserJet Pro MFP",
    category: "printers",
    price: 24999,
    image: printerImg,
    images: [printerImg, printerImg, printerImg],
    brand: "HP",
    specs: ["Laser Print/Scan/Copy", "40 ppm", "Auto Duplex", "Wi-Fi & Ethernet"],
    description: "All-in-one laser printer for busy offices. Fast, reliable, and cost-effective printing.",
    rating: 4.5,
    reviews: 567,
  },
  {
    id: "24",
    name: "Epson EcoTank L3250",
    category: "printers",
    price: 14999,
    originalPrice: 17999,
    image: printerImg,
    brand: "Epson",
    specs: ["Ink Tank Print/Scan/Copy", "33 ppm", "Borderless Photo", "Wi-Fi Direct"],
    description: "Ultra-low cost printing with refillable ink tanks. Perfect for home and small office use.",
    rating: 4.3,
    reviews: 891,
    badge: "Value Pick",
  },
  // New Seeds (16+)
  {
    id: "25",
    name: "MSI Raider GE78",
    category: "cpu-desktop",
    price: 189999,
    image: cpuDesktopImg,
    images: [cpuDesktopImg, cpuDesktopImg, cpuDesktopImg],
    brand: "MSI",
    ram: "32GB",
    storage: "2TB SSD",
    specs: ["Intel Core i9-14900HX", "32GB DDR5", "2TB NVMe SSD", "NVIDIA RTX 4080"],
    description: "The ultimate gaming machine with customizable RGB lighting and unparalleled performance.",
    rating: 4.9,
    reviews: 45,
    badge: "Flagship",
  },
  {
    id: "26",
    name: "Dell Precision 7000",
    category: "dell-laptop",
    price: 154999,
    image: dellLaptopImg,
    images: [dellLaptopImg, dellLaptopImg, dellLaptopImg],
    brand: "Dell",
    ram: "64GB",
    storage: "1TB SSD",
    specs: ["Intel Core i9-13950HX", "64GB DDR5", "1TB Gen4 SSD", "NVIDIA RTX A5000"],
    description: "A mobile workstation built for mission-critical tasks and resource-heavy software.",
    rating: 4.8,
    reviews: 12,
  },
  {
    id: "27",
    name: "HP Spectre Fallback",
    category: "hp-laptop",
    price: 89999,
    image: hpLaptopImg,
    brand: "HP",
    ram: "16GB",
    storage: "512GB SSD",
    specs: ["Intel Core i5-13500H", "16GB DDR4", "512GB SSD", "14\" Touch"],
    description: "Elegant design and reliable power, perfect for content creators on the go.",
    rating: 4.5,
    reviews: 104,
  },
  {
    id: "28",
    name: "Apple iMac 24\" M3",
    category: "cpu-desktop",
    price: 134900,
    image: macbookImg,
    images: [macbookImg, macbookImg],
    brand: "Apple",
    ram: "8GB",
    storage: "256GB SSD",
    specs: ["Apple M3 Chip (8-core CPU, 10-core GPU)", "8GB Unified Memory", "256GB SSD", "4.5K Retina Display"],
    description: "The world's best all-in-one desktop, supercharged by the powerful M3 chip.",
    rating: 4.9,
    reviews: 512,
    badge: "Sleek",
  },
  {
    id: "29",
    name: "Canon PIXMA G3010",
    category: "printers",
    price: 12900,
    image: printerImg,
    brand: "Canon",
    specs: ["All-in-One Ink Tank", "Print/Scan/Copy", "Wireless", "Cloud Link Support"],
    description: "High-yield ink tank printer for high-volume, low-cost printing.",
    rating: 4.2,
    reviews: 231,
  },
  {
    id: "30",
    name: "Lenovo Legion 7i",
    category: "lenovo-laptop",
    price: 169999,
    image: lenovoLaptopImg,
    images: [lenovoLaptopImg, lenovoLaptopImg, lenovoLaptopImg],
    brand: "Lenovo",
    ram: "32GB",
    storage: "1TB SSD",
    specs: ["Intel Core i9-13900HX", "32GB DDR5", "1TB SSD", "NVIDIA RTX 4070"],
    description: "World-class gaming laptop with premium aluminum design and high-refresh display.",
    rating: 4.7,
    reviews: 87,
    badge: "Gamer Choice",
  },
  {
    id: "31",
    name: "Dell Inspiron 16 Plus",
    category: "dell-laptop",
    price: 109999,
    image: dellLaptopImg,
    brand: "Dell",
    ram: "32GB",
    storage: "1TB SSD",
    specs: ["Intel Core i7-13700H", "32GB DDR5", "1TB SSD", "16\" 2.5K 120Hz"],
    description: "Crafted for creators. A large 16-inch display for your biggest ideas.",
    rating: 4.6,
    reviews: 56,
  },
  {
    id: "32",
    name: "HP Omen Transcribe",
    category: "hp-laptop",
    price: 144999,
    image: hpLaptopImg,
    images: [hpLaptopImg, hpLaptopImg],
    brand: "HP",
    ram: "16GB",
    storage: "1TB SSD",
    specs: ["Intel Core i9-13900K", "16GB DDR5", "1TB SSD", "NVIDIA RTX 4080"],
    description: "Next-gen gaming performance in a portable design for pro players.",
    rating: 4.8,
    reviews: 32,
  },
  {
    id: "33",
    name: "Brother MFC-L2701D",
    category: "printers",
    price: 18450,
    image: printerImg,
    brand: "Brother",
    specs: ["Laser All-in-One", "Auto Duplex", "30 ppm", "Fast ID Copy"],
    description: "Reliable monochromatic laser printer with all-in-one functions.",
    rating: 4.4,
    reviews: 145,
  },
  {
    id: "34",
    name: "Mac Studio M2 Max",
    category: "cpu-desktop",
    price: 209900,
    image: cpuDesktopImg,
    images: [cpuDesktopImg, cpuDesktopImg, cpuDesktopImg],
    brand: "Apple",
    ram: "32GB",
    storage: "512GB SSD",
    specs: ["Apple M2 Max (12-core CPU, 30-core GPU)", "32GB Unified Memory", "512GB SSD", "Compact Form Factor"],
    description: "Performance in a compact frame for creative professionals to transform any desk into a powerhouse studio.",
    rating: 5.0,
    reviews: 21,
    badge: "Workstation",
  },
  {
    id: "35",
    name: "Dell Vostro 15 3000",
    category: "dell-laptop",
    price: 36999,
    image: dellLaptopImg,
    brand: "Dell",
    ram: "8GB",
    storage: "256GB SSD",
    specs: ["Intel Core i3-1215U", "8GB DDR4", "256GB SSD", "15.6\" HD"],
    description: "Reliable performance for small business needs. Essential features for your office.",
    rating: 4.1,
    reviews: 112,
  },
  {
    id: "36",
    name: "HP Envy Move All-in-One",
    category: "cpu-desktop",
    price: 84999,
    image: cpuDesktopImg,
    brand: "HP",
    ram: "16GB",
    storage: "512GB SSD",
    specs: ["Intel Core i5-1335U", "16GB LPDDR5", "512GB NVMe SSD", "23.8\" QHD Touch Screen"],
    description: "The world's only movable all-in-one with a built-in battery. Work anywhere.",
    rating: 4.4,
    reviews: 18,
    badge: "Unique",
  },
  {
    id: "37",
    name: "Lenovo Yoga Book 9i",
    category: "lenovo-laptop",
    price: 199999,
    image: lenovoLaptopImg,
    images: [lenovoLaptopImg, lenovoLaptopImg, lenovoLaptopImg],
    brand: "Lenovo",
    ram: "16GB",
    storage: "1TB SSD",
    specs: ["Intel Core i7-1355U", "16GB LPDDR5x", "1TB SSD", "Dual 13.3\" 2.8K OLED Displays"],
    description: "The world's first full-screen dual-display laptop for maximum productivity on the go.",
    rating: 4.9,
    reviews: 67,
    badge: "Innovation",
  },
  {
    id: "38",
    name: "HP Smart Tank 580",
    category: "printers",
    price: 15450,
    image: printerImg,
    brand: "HP",
    specs: ["Print/Scan/Copy", "Inbuilt Wi-Fi", "Hi-speed USB 2.0", "Low Cost Per Page"],
    description: "Print thousands of pages per ink bottle with this high-volume ink tank printer.",
    rating: 4.5,
    reviews: 210,
  },
  {
    id: "39",
    name: "Dell Inspiron Desktop",
    category: "cpu-desktop",
    price: 45999,
    image: cpuDesktopImg,
    brand: "Dell",
    ram: "16GB",
    storage: "512GB SSD+1TB HDD",
    specs: ["Intel Core i5-13400", "16GB DDR4", "512GB SSD + 1TB HDD", "Space-saving Design"],
    description: "Versatile desktop for home and office. Built for solid performance and easy expandability.",
    rating: 4.3,
    reviews: 89,
  },
  {
    id: "40",
    name: "Lenovo Tab Extreme",
    category: "lenovo-laptop",
    price: 89999,
    image: lenovoLaptopImg,
    brand: "Lenovo",
    ram: "12GB",
    storage: "256GB SSD",
    specs: ["MediaTek Dimensity 9000", "12GB LPDDR5X", "256GB SSD", "14.5\" 3K OLED Display"],
    description: "A massive, powerful tablet that doubles as a laptop with its premium keyboard and large screen.",
    rating: 4.7,
    reviews: 34,
  },
];

export const testimonials = [
  {
    name: "Arjun Mehta",
    role: "Software Architect",
    text: "The Studio Tower Pro transformed my development workflow. Builds that took 20 minutes now finish in under 3. Chauhan's attention to detail is unmatched.",
    rating: 5,
  },
  {
    name: "Priya Sharma",
    role: "Digital Artist",
    text: "I've tried every brand. Chauhan is the only one that delivers true professional-grade hardware with a premium experience from unboxing to daily use.",
    rating: 5,
  },
  {
    name: "Karan Singh",
    role: "Business Owner",
    text: "From laptop purchases to CCTV installation, Chauhan Computers handles everything for my office. Their service is outstanding.",
    rating: 5,
  },
];

export const blogPosts = [
  {
    id: "1",
    title: "How to Choose the Right Laptop for Your Needs in 2026",
    excerpt: "A comprehensive guide to selecting the perfect laptop based on your usage, budget, and preferences.",
    date: "March 15, 2026",
    category: "Guides",
    readTime: "5 min read",
  },
  {
    id: "2",
    title: "Top 5 Desktop Setups for Remote Work",
    excerpt: "Boost your productivity with these curated desktop configurations designed for the modern remote worker.",
    date: "March 10, 2026",
    category: "Productivity",
    readTime: "4 min read",
  },
  {
    id: "3",
    title: "Why Regular Computer Maintenance Matters",
    excerpt: "Learn how routine servicing can extend your computer's lifespan and keep it running at peak performance.",
    date: "March 5, 2026",
    category: "Maintenance",
    readTime: "3 min read",
  },
  {
    id: "4",
    title: "MacBook vs Windows Laptop: Which Should You Buy?",
    excerpt: "An honest comparison between MacBook and Windows laptops to help you make the right choice.",
    date: "February 28, 2026",
    category: "Comparison",
    readTime: "6 min read",
  },
  {
    id: "5",
    title: "Setting Up a Home CCTV System: Complete Guide",
    excerpt: "Everything you need to know about choosing, installing, and maintaining a home security camera system.",
    date: "February 20, 2026",
    category: "Security",
    readTime: "7 min read",
  },
];
