import dellLaptopImg from "@/assets/dell-laptop.png";
import hpLaptopImg from "@/assets/hp-laptop.png";
import lenovoLaptopImg from "@/assets/lenovo-laptop.png";
import macbookImg from "@/assets/macbook.png";
import cpuDesktopImg from "@/assets/cpu-desktop.png";
import printerImg from "@/assets/printer.png";
import serviceLaptopImg from "@/assets/service-laptop-repair.png";
import servicePrinterImg from "@/assets/service-printer-repair.png";
import serviceCpuImg from "@/assets/service-cpu-repair.png";
import serviceCctvImg from "@/assets/service-cctv.png";

export interface Product {
  id: string;
  name: string;
  category: string;
  price: number;
  originalPrice?: number;
  image: string;
  brand: string;
  ram?: string;
  storage?: string;
  specs: string[];
  description: string;
  rating: number;
  reviews: number;
  badge?: string;
}

export const categories = [
  { name: "CPU | Desktop Setup", slug: "cpu-desktop", image: cpuDesktopImg },
  { name: "Dell Laptop", slug: "dell-laptop", image: dellLaptopImg },
  { name: "HP Laptop", slug: "hp-laptop", image: hpLaptopImg },
  { name: "Lenovo Laptop", slug: "lenovo-laptop", image: lenovoLaptopImg },
  { name: "MacBook", slug: "macbook", image: macbookImg },
  { name: "Printers", slug: "printers", image: printerImg },
];

export interface Service {
  id: string;
  name: string;
  description: string;
  image: string;
  icon: string;
}

export const services: Service[] = [
  {
    id: "laptop-repair",
    name: "Laptop Repair",
    description: "Expert diagnosis and repair for all laptop brands. Screen replacement, keyboard repair, motherboard fixing, and more.",
    image: serviceLaptopImg,
    icon: "laptop",
  },
  {
    id: "printer-repair",
    name: "Printer Repair",
    description: "Professional printer servicing and repair. Ink system fixes, paper jam solutions, and regular maintenance.",
    image: servicePrinterImg,
    icon: "printer",
  },
  {
    id: "cpu-repair",
    name: "CPU Repair",
    description: "Desktop and CPU troubleshooting, hardware upgrades, OS installation, and performance optimization.",
    image: serviceCpuImg,
    icon: "cpu",
  },
  {
    id: "cctv-installation",
    name: "CCTV Installation",
    description: "Complete CCTV setup and installation. HD cameras, DVR/NVR configuration, and remote monitoring setup.",
    image: serviceCctvImg,
    icon: "camera",
  },
];

export const products: Product[] = [
  // CPU | Desktop Setup (5)
  {
    id: "1",
    name: "ProDesk Elite i9",
    category: "cpu-desktop",
    price: 89999,
    originalPrice: 99999,
    image: cpuDesktopImg,
    brand: "Chauhaan",
    ram: "32GB",
    storage: "1TB SSD",
    specs: ["Intel Core i9-14900K", "32GB DDR5", "1TB NVMe SSD", "NVIDIA RTX 4070"],
    description: "High-performance desktop workstation built for professionals who demand uncompromising power.",
    rating: 4.9,
    reviews: 124,
    badge: "Best Seller",
  },
  {
    id: "2",
    name: "Studio Tower Pro",
    category: "cpu-desktop",
    price: 74999,
    image: cpuDesktopImg,
    brand: "Chauhaan",
    ram: "64GB",
    storage: "2TB SSD",
    specs: ["AMD Ryzen 9 7950X", "64GB DDR5", "2TB NVMe SSD", "NVIDIA RTX 4080"],
    description: "Built for creative professionals. Handles 8K editing, 3D rendering, and complex simulations with ease.",
    rating: 4.8,
    reviews: 87,
    badge: "New",
  },
  {
    id: "3",
    name: "Compact Workstation",
    category: "cpu-desktop",
    price: 54999,
    image: cpuDesktopImg,
    brand: "Chauhaan",
    ram: "32GB",
    storage: "1TB SSD",
    specs: ["Intel Core i7-14700", "32GB DDR5", "1TB NVMe SSD", "Intel Arc A770"],
    description: "Big performance in a small form factor. Fits anywhere without compromise.",
    rating: 4.5,
    reviews: 67,
  },
  {
    id: "4",
    name: "Gaming Beast X",
    category: "cpu-desktop",
    price: 129999,
    image: cpuDesktopImg,
    brand: "Chauhaan",
    ram: "32GB",
    storage: "2TB SSD",
    specs: ["Intel Core i9-14900K", "32GB DDR5", "2TB NVMe SSD", "NVIDIA RTX 4090"],
    description: "Dominate every game with desktop-class performance and custom liquid cooling.",
    rating: 4.9,
    reviews: 203,
  },
  {
    id: "5",
    name: "Office Desktop Basic",
    category: "cpu-desktop",
    price: 32999,
    image: cpuDesktopImg,
    brand: "Chauhaan",
    ram: "16GB",
    storage: "512GB SSD",
    specs: ["Intel Core i5-14400", "16GB DDR5", "512GB NVMe SSD", "Intel UHD 730"],
    description: "Reliable everyday computing for office and home use. Quiet and efficient.",
    rating: 4.3,
    reviews: 312,
  },

  // Dell Laptop (5)
  {
    id: "6",
    name: "Dell Inspiron 15",
    category: "dell-laptop",
    price: 49999,
    originalPrice: 55999,
    image: dellLaptopImg,
    brand: "Dell",
    ram: "16GB",
    storage: "512GB SSD",
    specs: ["Intel Core i5-1335U", "16GB DDR5", "512GB NVMe SSD", "15.6\" FHD IPS"],
    description: "Versatile everyday laptop with solid performance and vibrant display for work and entertainment.",
    rating: 4.4,
    reviews: 456,
    badge: "Popular",
  },
  {
    id: "7",
    name: "Dell Latitude 14",
    category: "dell-laptop",
    price: 72999,
    image: dellLaptopImg,
    brand: "Dell",
    ram: "16GB",
    storage: "512GB SSD",
    specs: ["Intel Core i7-1365U", "16GB DDR5", "512GB NVMe SSD", "14\" FHD+"],
    description: "Business-grade laptop built for security, manageability, and all-day battery life.",
    rating: 4.6,
    reviews: 189,
  },
  {
    id: "8",
    name: "Dell XPS 15",
    category: "dell-laptop",
    price: 134999,
    originalPrice: 149999,
    image: dellLaptopImg,
    brand: "Dell",
    ram: "32GB",
    storage: "1TB SSD",
    specs: ["Intel Core i7-13700H", "32GB DDR5", "1TB NVMe SSD", "15.6\" 3.5K OLED"],
    description: "Premium ultrabook with stunning OLED display and powerhouse performance in a thin design.",
    rating: 4.8,
    reviews: 298,
    badge: "Premium",
  },
  {
    id: "9",
    name: "Dell Vostro 14",
    category: "dell-laptop",
    price: 44999,
    image: dellLaptopImg,
    brand: "Dell",
    ram: "8GB",
    storage: "512GB SSD",
    specs: ["Intel Core i5-1335U", "8GB DDR4", "512GB NVMe SSD", "14\" FHD"],
    description: "Small business laptop with essential features and reliable performance at a great value.",
    rating: 4.2,
    reviews: 134,
  },
  {
    id: "10",
    name: "Dell G15 Gaming",
    category: "dell-laptop",
    price: 89999,
    image: dellLaptopImg,
    brand: "Dell",
    ram: "16GB",
    storage: "1TB SSD",
    specs: ["Intel Core i7-13650HX", "16GB DDR5", "1TB NVMe SSD", "NVIDIA RTX 4060"],
    description: "Gaming laptop with high-refresh display and powerful graphics for immersive gameplay.",
    rating: 4.5,
    reviews: 267,
    badge: "Gaming",
  },

  // HP Laptop (4)
  {
    id: "11",
    name: "HP Pavilion 15",
    category: "hp-laptop",
    price: 47999,
    originalPrice: 52999,
    image: hpLaptopImg,
    brand: "HP",
    ram: "16GB",
    storage: "512GB SSD",
    specs: ["AMD Ryzen 5 7530U", "16GB DDR4", "512GB NVMe SSD", "15.6\" FHD IPS"],
    description: "Everyday laptop with AMD power, vibrant display, and sleek design for work and play.",
    rating: 4.3,
    reviews: 389,
  },
  {
    id: "12",
    name: "HP EliteBook 840",
    category: "hp-laptop",
    price: 94999,
    image: hpLaptopImg,
    brand: "HP",
    ram: "16GB",
    storage: "512GB SSD",
    specs: ["Intel Core i7-1365U", "16GB DDR5", "512GB NVMe SSD", "14\" WUXGA"],
    description: "Enterprise-grade ultrabook with advanced security features and premium build quality.",
    rating: 4.7,
    reviews: 156,
    badge: "Business",
  },
  {
    id: "13",
    name: "HP Spectre x360",
    category: "hp-laptop",
    price: 119999,
    image: hpLaptopImg,
    brand: "HP",
    ram: "16GB",
    storage: "1TB SSD",
    specs: ["Intel Core i7-1355U", "16GB LPDDR5", "1TB NVMe SSD", "13.5\" 3K2K OLED"],
    description: "Stunning convertible laptop with gem-cut design and brilliant OLED touchscreen.",
    rating: 4.8,
    reviews: 201,
    badge: "Premium",
  },
  {
    id: "14",
    name: "HP Victus 16 Gaming",
    category: "hp-laptop",
    price: 79999,
    originalPrice: 89999,
    image: hpLaptopImg,
    brand: "HP",
    ram: "16GB",
    storage: "512GB SSD",
    specs: ["AMD Ryzen 7 7840HS", "16GB DDR5", "512GB NVMe SSD", "NVIDIA RTX 4050"],
    description: "Affordable gaming laptop with solid performance and 144Hz display for smooth gameplay.",
    rating: 4.4,
    reviews: 312,
    badge: "Value",
  },

  // Lenovo Laptop (2)
  {
    id: "15",
    name: "Lenovo ThinkPad X1 Carbon",
    category: "lenovo-laptop",
    price: 139999,
    image: lenovoLaptopImg,
    brand: "Lenovo",
    ram: "16GB",
    storage: "512GB SSD",
    specs: ["Intel Core i7-1365U", "16GB LPDDR5", "512GB NVMe SSD", "14\" 2.8K OLED"],
    description: "The gold standard in business ultrabooks. Ultra-light, ultra-durable, ultra-premium.",
    rating: 4.9,
    reviews: 445,
    badge: "Editor's Choice",
  },
  {
    id: "16",
    name: "Lenovo IdeaPad Slim 5",
    category: "lenovo-laptop",
    price: 54999,
    originalPrice: 59999,
    image: lenovoLaptopImg,
    brand: "Lenovo",
    ram: "16GB",
    storage: "512GB SSD",
    specs: ["AMD Ryzen 5 7530U", "16GB DDR4", "512GB NVMe SSD", "15.6\" FHD IPS"],
    description: "Slim and stylish everyday laptop with great battery life and performance for students and professionals.",
    rating: 4.4,
    reviews: 278,
  },

  // MacBook (6)
  {
    id: "17",
    name: "MacBook Air M2",
    category: "macbook",
    price: 99999,
    originalPrice: 114999,
    image: macbookImg,
    brand: "Apple",
    ram: "8GB",
    storage: "256GB SSD",
    specs: ["Apple M2 Chip", "8GB Unified Memory", "256GB SSD", "13.6\" Liquid Retina"],
    description: "Supercharged by M2 chip. Strikingly thin design with incredible performance and all-day battery life.",
    rating: 4.8,
    reviews: 892,
    badge: "Popular",
  },
  {
    id: "18",
    name: "MacBook Air M3",
    category: "macbook",
    price: 114999,
    image: macbookImg,
    brand: "Apple",
    ram: "8GB",
    storage: "256GB SSD",
    specs: ["Apple M3 Chip", "8GB Unified Memory", "256GB SSD", "13.6\" Liquid Retina"],
    description: "The most popular Mac, now with the M3 chip. Impossibly thin with stunning performance.",
    rating: 4.9,
    reviews: 567,
    badge: "New",
  },
  {
    id: "19",
    name: "MacBook Pro 14\" M3",
    category: "macbook",
    price: 169999,
    image: macbookImg,
    brand: "Apple",
    ram: "18GB",
    storage: "512GB SSD",
    specs: ["Apple M3 Pro Chip", "18GB Unified Memory", "512GB SSD", "14.2\" Liquid Retina XDR"],
    description: "Pro-level performance for demanding workflows. XDR display with ProMotion for the ultimate experience.",
    rating: 4.9,
    reviews: 723,
    badge: "Pro",
  },
  {
    id: "20",
    name: "MacBook Pro 16\" M3 Max",
    category: "macbook",
    price: 299999,
    image: macbookImg,
    brand: "Apple",
    ram: "36GB",
    storage: "1TB SSD",
    specs: ["Apple M3 Max Chip", "36GB Unified Memory", "1TB SSD", "16.2\" Liquid Retina XDR"],
    description: "The most powerful MacBook ever. Built for professionals who push the boundaries of what's possible.",
    rating: 5.0,
    reviews: 334,
    badge: "Ultimate",
  },
  {
    id: "21",
    name: "MacBook Air 15\" M3",
    category: "macbook",
    price: 134999,
    image: macbookImg,
    brand: "Apple",
    ram: "8GB",
    storage: "256GB SSD",
    specs: ["Apple M3 Chip", "8GB Unified Memory", "256GB SSD", "15.3\" Liquid Retina"],
    description: "Big, beautiful 15-inch display in an impossibly thin design. Perfect for multitasking.",
    rating: 4.7,
    reviews: 445,
  },
  {
    id: "22",
    name: "MacBook Pro 14\" M3 Pro",
    category: "macbook",
    price: 199999,
    originalPrice: 219999,
    image: macbookImg,
    brand: "Apple",
    ram: "18GB",
    storage: "1TB SSD",
    specs: ["Apple M3 Pro Chip", "18GB Unified Memory", "1TB SSD", "14.2\" Liquid Retina XDR"],
    description: "Enhanced M3 Pro with more storage. The professional's choice for creative work.",
    rating: 4.9,
    reviews: 198,
    badge: "Best Value",
  },

  // Printers (2)
  {
    id: "23",
    name: "HP LaserJet Pro MFP",
    category: "printers",
    price: 24999,
    image: printerImg,
    brand: "HP",
    specs: ["Laser Print/Scan/Copy", "40 ppm", "Auto Duplex", "Wi-Fi & Ethernet"],
    description: "All-in-one laser printer for busy offices. Fast, reliable, and cost-effective printing.",
    rating: 4.5,
    reviews: 567,
  },
  {
    id: "24",
    name: "Epson EcoTank L3250",
    category: "printers",
    price: 14999,
    originalPrice: 17999,
    image: printerImg,
    brand: "Epson",
    specs: ["Ink Tank Print/Scan/Copy", "33 ppm", "Borderless Photo", "Wi-Fi Direct"],
    description: "Ultra-low cost printing with refillable ink tanks. Perfect for home and small office use.",
    rating: 4.3,
    reviews: 891,
    badge: "Value Pick",
  },
];

export const testimonials = [
  {
    name: "Arjun Mehta",
    role: "Software Architect",
    text: "The Studio Tower Pro transformed my development workflow. Builds that took 20 minutes now finish in under 3. Chauhaan's attention to detail is unmatched.",
    rating: 5,
  },
  {
    name: "Priya Sharma",
    role: "Digital Artist",
    text: "I've tried every brand. Chauhaan is the only one that delivers true professional-grade hardware with a premium experience from unboxing to daily use.",
    rating: 5,
  },
  {
    name: "Karan Singh",
    role: "Business Owner",
    text: "From laptop purchases to CCTV installation, Chauhaan Computers handles everything for my office. Their service is outstanding.",
    rating: 5,
  },
];

export const blogPosts = [
  {
    id: "1",
    title: "How to Choose the Right Laptop for Your Needs in 2026",
    excerpt: "A comprehensive guide to selecting the perfect laptop based on your usage, budget, and preferences.",
    date: "March 15, 2026",
    category: "Guides",
    readTime: "5 min read",
  },
  {
    id: "2",
    title: "Top 5 Desktop Setups for Remote Work",
    excerpt: "Boost your productivity with these curated desktop configurations designed for the modern remote worker.",
    date: "March 10, 2026",
    category: "Productivity",
    readTime: "4 min read",
  },
  {
    id: "3",
    title: "Why Regular Computer Maintenance Matters",
    excerpt: "Learn how routine servicing can extend your computer's lifespan and keep it running at peak performance.",
    date: "March 5, 2026",
    category: "Maintenance",
    readTime: "3 min read",
  },
  {
    id: "4",
    title: "MacBook vs Windows Laptop: Which Should You Buy?",
    excerpt: "An honest comparison between MacBook and Windows laptops to help you make the right choice.",
    date: "February 28, 2026",
    category: "Comparison",
    readTime: "6 min read",
  },
  {
    id: "5",
    title: "Setting Up a Home CCTV System: Complete Guide",
    excerpt: "Everything you need to know about choosing, installing, and maintaining a home security camera system.",
    date: "February 20, 2026",
    category: "Security",
    readTime: "7 min read",
  },
];
